### ISSUE TITLE
potential footgun regarding parenthesization and `.or`

### ISSUE THREAD

**Issue by Roguelazer** [MaxLap/activerecord_where_assoc#12]
This is kind of tough to explain.

Imagine you had the following models:

```ruby
class Project < ApplicationRecord
  belongs_to :account
end

class Account < ApplicationRecord
  has_many :projects

  scope :foo, -> do
    where(attribute: "value").or(Account.bar)
  end

  scope :bar, -> do
    where(other_attribute: "other_value")
  end
end
```

a query like `Project.where_assoc_exists(:account, &:foo)` contains a surprising footgun: it doesn't include the second part of the OR in the parentheses. You end up with something like:

```sql
SELECT * FROM projects WHERE EXISTS (SELECT 1 FROM "accounts" WHERE ("accounts"."id" = "projects"."account_id" AND "accounts"."attribute" = 'value') OR "accounts"."other_attribute" = 'other_value'))
```

This is somewhat surprising! The fix is to change the scope `foo` to

```ruby
scope :foo:, -> do
  where(attribute: "value").or(merge(Account.bar))
end
```

Then you get the expect SQL

```sql
SELECT * FROM projects WHERE EXISTS (SELECT 1 FROM "accounts" WHERE "accounts"."id" = "projects"."account_id" AND ("accounts"."attribute" = 'value' OR "accounts"."other_attribute" = 'other_value'))
```

Both versions generate the exact same SQL if you call `Account.foo`, so I'm pretty sure this is a `where_assoc_exists` bug

**Comment by MaxLap** [comment]
Alright, that took a few hours of investigations, but I got an answer... The short answer is that your scope is wrong. Weird, I know.

I'm going to assume you are in Rails 6.1 or above because that the only time I could reproduce this and Rails 6.1 changes something about that.

Here is the change: https://guides.rubyonrails.org/6_1_release_notes.html#active-record-notable-changes
> Named scope chain does no longer leak scope to class-level querying methods.
```
class User < ActiveRecord::Base
  scope :david, -> { User.where(name: "David") }
end
```
> Before:
```
User.where(name: "John").david
# SELECT * FROM users WHERE name = 'John' AND name = 'David'
```
> After:
```
User.where(name: "John").david
# SELECT * FROM users WHERE name = 'David'
```

I didn't see it mentioned in the upgrade guide, but it seems important to me.

It's a dangerous change, as you can see. In the scope's proc, `self` keeps on behaving as the relation on which the scope was called. But the constants, `User` in that case, behave as clean relations. So in that example, you totally lose the filters that were applied before.

I applaud the change, because I always hated the occasional need for unscoped and that seeming magic. But now that's a lot of code that may be subtly wrong or slower.

So for your problem, you mention using `merge` as a fix, but really you should just not be using `Account`. This should work:
```
scope :foo:, -> do
  where(attribute: "value").or(bar)
end
```

Coincidentally, I'm upgrading an app to 6.1 for work so learning this now is great timing! Thanks

**Comment by Roguelazer** [comment]
That makes sense; this code was introduced on 5.x and I guess we never noticed that change in 6.1. It's a shame rails doesn't emit a warning when you do something quite so surprising!

**Comment by MaxLap** [comment]
Yeah, I'm quite surprised by such a change with no deprecation / warning. I'm thinking of maybe making a custom RuboCop cop which could detect scopes like these. I'll see when I get to that in my todo list.
