### ISSUE TITLE
using .count on a where_assoc_exists relation is very slow

### ISSUE THREAD

**Issue by anark** [MaxLap/activerecord_where_assoc#8]
Hi there,
I'm trying to use this gem to speed up filtering via association presence.  In general it works great(and is even faster than using counter cache columns in some cases), however I am noticing that if you call `.count` on a relation it is very slow.

`Post.where_assoc_exists([:comments, :author]).count`

Is there anyway to speed up getting a count like this using this gem?

**Comment by MaxLap** [comment]
Hello, glad you find the gem useful!

It's not clear what you mean by "very slow", it could mean 5ms, which is very slow compared to 0.5ms, or it could means 5 seconds.

So here is a general answer: doing a count over all the records in the database can be slow if it contains too many records. In Postgres, just `Post.count` can take seconds if you have millions of records.

If the slowdown really comes from the filtering by association, then that could be caused by missing indexes in your database.

Taking your example, you should have an index on `comments.post_id`, and it's possible that having one on `comments.author_id` would also help. At this point, it's really about database optimization.

As a side note, I would assume that every comment should have an author, so just doing `Post.where_assoc_exists(:comments).count` should give the same result and be lighter. But maybe that was just a simple example for a more complex problem.

**Comment by anark** [comment]
Thanks @MaxLap,
On large tables with complicated queries it was taking over 30 seconds, however it looks like any other version of the count query is similar(when not cached).

After further investigation this is not an issue with where_assoc.  The best solution(if possible) is to remove the need for full counts.
